executable      = $ENV(STARTDIR)/condor/condorHistos_executable.sh
output          = $ENV(STARTDIR)/condor/plotting_logs/job.$(ClusterId).$(ProcId).out
error           = $ENV(STARTDIR)/condor/plotting_logs/job.$(ClusterId).$(ProcId).err
log             = $ENV(STARTDIR)/condor/plotting_logs/job.$(ClusterId).$(ProcId).log

RequestCpus   = 2
RequestMemory = 8000

getenv = True
#+JobFlavour = "longlunch"
+JobFlavour = "workday"
+DESIRED_Sites = "T2_US_UCSD"
transfer_input_files = $ENV(STARTDIR)/package.tar.gz
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
x509userproxy=$ENV(X509_USER_PROXY)
use_x509userproxy = True

# Comment out any of the following configurations
queue arguments from (
###
# ScenarioA
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-10_MA-2p00_ctau-0p1mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-10_MA-2p00_ctau-10mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-10_MA-2p00_ctau-100mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-10_MA-2p00_ctau-1p0mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-10_MA-4p90_ctau-0p1mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-10_MA-4p90_ctau-10mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-10_MA-4p90_ctau-100mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-10_MA-4p90_ctau-1p0mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-2_MA-0p67_ctau-0p1mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-2_MA-0p67_ctau-10mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-2_MA-0p67_ctau-100mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-2_MA-0p67_ctau-1p0mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-4_MA-1p33_ctau-0p1mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-4_MA-1p33_ctau-10mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-4_MA-1p33_ctau-100mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-4_MA-1p33_ctau-1p0mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-4_MA-1p90_ctau-0p1mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-4_MA-1p90_ctau-100mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-4_MA-1p90_ctau-1p0mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-5_MA-1p67_ctau-0p1mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-5_MA-1p67_ctau-10mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-5_MA-1p67_ctau-100mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-5_MA-1p67_ctau-1p0mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-5_MA-2p40_ctau-0p1mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-5_MA-2p40_ctau-10mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-5_MA-2p40_ctau-100mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
#
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-10_MA-2p00_ctau-0p1mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-10_MA-2p00_ctau-10mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-10_MA-2p00_ctau-100mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-10_MA-2p00_ctau-1p0mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-10_MA-4p90_ctau-0p1mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-10_MA-4p90_ctau-10mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-10_MA-4p90_ctau-100mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-10_MA-4p90_ctau-1p0mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-2_MA-0p67_ctau-0p1mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-2_MA-0p67_ctau-10mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-2_MA-0p67_ctau-100mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-2_MA-0p67_ctau-1p0mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-4_MA-1p33_ctau-0p1mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-4_MA-1p33_ctau-1p0mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-4_MA-1p90_ctau-10mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-4_MA-1p90_ctau-100mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-4_MA-1p90_ctau-1p0mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-5_MA-1p67_ctau-0p1mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-5_MA-1p67_ctau-10mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-5_MA-1p67_ctau-100mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-5_MA-1p67_ctau-1p0mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-5_MA-2p40_ctau-0p1mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-5_MA-2p40_ctau-100mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioA_Mpi-5_MA-2p40_ctau-1p0mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
#
# ScenarioB1
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-2_MA-0p67_ctau-10mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-2_MA-0p67_ctau-100mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-2_MA-0p67_ctau-1p0mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-4_MA-0p67_ctau-0p1mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-4_MA-0p67_ctau-100mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-4_MA-0p67_ctau-1p0mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-4_MA-1p33_ctau-0p1mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-4_MA-1p33_ctau-10mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-4_MA-1p33_ctau-100mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-4_MA-1p33_ctau-1p0mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-4_MA-1p90_ctau-0p1mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-4_MA-1p90_ctau-10mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-4_MA-1p90_ctau-100mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-4_MA-1p90_ctau-1p0mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-5_MA-1p67_ctau-0p1mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-5_MA-1p67_ctau-10mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-5_MA-1p67_ctau-100mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-5_MA-1p67_ctau-1p0mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-5_MA-2p40_ctau-0p1mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-5_MA-2p40_ctau-10mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-5_MA-2p40_ctau-100mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-5_MA-2p40_ctau-1p0mm_2023 --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
#
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-2_MA-0p67_ctau-0p1mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-2_MA-0p67_ctau-10mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-2_MA-0p67_ctau-100mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-2_MA-0p67_ctau-1p0mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-4_MA-0p67_ctau-0p1mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-4_MA-0p67_ctau-10mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-4_MA-0p67_ctau-100mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-4_MA-0p67_ctau-1p0mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-4_MA-1p90_ctau-0p1mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-4_MA-1p90_ctau-10mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-4_MA-1p90_ctau-100mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-4_MA-1p90_ctau-1p0mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-5_MA-1p67_ctau-0p1mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-5_MA-1p67_ctau-10mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-5_MA-1p67_ctau-1p0mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-5_MA-2p40_ctau-10mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
$ENV(SCOUTINGINPUTDIR) $ENV(SCOUTINGOUTPUTDIR) --condor --signal --year 2023 --noSeed L1_DoubleMu_12_5 --inSample Signal_ScenarioB1_Mpi-5_MA-2p40_ctau-100mm_2023BPix --splitIndex 0 --splitPace 1000000 $ENV(SCOUTINGARGS)
#
)

#1000000
#3765643

#From event 0 to event 25866581
#From event 0 to event 13167789

#python3 fillHistosScouting.py --inDir /ceph/cms/store/user/legianni/Run3ScoutingOutput/looperOutput_Sep-21-2023/  --outSuffix test --year 2023 --inSample DataB
